[package]
name = "rbspy"
version = "0.25.0"
authors = ["Adam Jensen <acjensen@gmail.com>", "Julia Evans <julia@jvns.ca>"]
description = "Sampling CPU profiler for Ruby"
keywords = ["ruby", "profiler", "MRI"]
license = "MIT"
repository = "https://github.com/rbspy/rbspy"
readme = "README.md"
documentation = "https://github.com/rbspy/rbspy"
homepage = "https://rbspy.github.io/"
edition = "2021"
exclude = ["/.github/", "/ci/", "/xtask/"]
rust-version = "1.56"

[workspace]
members = [
    "ruby-structs",
    "xtask",
]

[dependencies]
anyhow = "1.0.58"
chrono = { version = "0.4.24", default-features = false, features = ["clock", "std"] }
clap = { version = "4.2.7", features = ["derive"] }
ctrlc = "3.1.0"
directories = "5.0.0"
env_logger = "0.11.2"
inferno = "0.11.1"
flate2 = "1.0.20"
lazy_static = "1.4"
libc = "0.2.34"
log = "0.4.6"
memmap2 = "0.9.3"
proc-maps = "0.3.0"
prost = "0.13.0"
rand = "0.8.3"
rbspy-ruby-structs = { path = "ruby-structs", version="0.25.0" }
remoteprocess = "0.4.5"
semver = "1.0.10"
serde = "1.0.131"
serde_derive = "1.0.131"
serde_json = "1.0.72"
spytools = "0.2.0"
term_size = "0.3.2"
tempfile = "3.4.0"
thiserror = "1.0.24"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["user"] }

[target.'cfg(target_os="macos")'.dependencies]
libproc = "0.14.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["timeapi", "wow64apiset"] }

[dev-dependencies]
byteorder = "1.4.3"
rbspy-testdata = "0.2.1"
